import type { Metadata } from "next";
import localFont from "next/font/local";
import { CustomProviders } from "./Provider";
import "./globals.css";
import Nav from "./components/Nav";
import { MovieProvider } from "./components/context/MovieContext";
import { connectMongoDB } from "@/lib/db";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await connectMongoDB();
  return (
    <CustomProviders>
      <html lang="en">
      <MovieProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Nav />
          {children}
        </body>
        </MovieProvider>
      </html>
    </CustomProviders>
  );
}
